### ISSUE TITLE
todo list for completion of seccomp-pledge

### ISSUE THREAD

**Issue by sn99** [SubconsciousCompute/seccomp-pledge#1]
Great work on the project and related materials, @DeviousCilantro! 🎉 Keep up the good work. We're now going to use this issue to create a checklist of small tasks that still need to be done.

- [x] Run `cargo clippy -- -W clippy::pedantic` and apply appropriate changes (you might wanna read all of them as some might cause regression, you can apply them automatically using `cargo clippy --fix -- -W clippy::pedantic` but best to go through them)
- [x] Move checks for BIF JIT, dependencies, etc. out of the `fn main` function. This way, we can avoid a bit of overhead. Instead, we should ideally have a `fn check()` function that is called through a command line argument, such as `-check` or `-no_check`.
- [x] Tests: We can launch commands like `ls` with and without restrictions (`ls` the project folder) to see if we get the expected output.
- [x] Benchmarks: While there may not be a specific need for them, we will include tests in the benchmarking process for the sake of completeness.
- [x] Non-interactive mode: The current program runs in an interactive way, but we should also have a simple one-liner, for example: `./seccomp_pledge -check -v -p 'stdio rpath' ls` similar to `pledge`.
- [x] Add more examples in `README`

Don't worry about `CI` and other things, I will update the project with it, along with the skeleton for tests and benchmarks. A few good starting points for you might be:

A few good starting points for you might be: 
- [writing tests](https://doc.rust-lang.org/book/ch11-01-writing-tests.html) and [writing tests for command line](https://rust-cli.github.io/book/tutorial/testing.html)
- [benchmarking](https://bheisler.github.io/criterion.rs/book/getting_started.html), just throw every test inside `blackbox`
- [Command Line Applications in Rust](https://rust-cli.github.io/book/index.html)

**Comment by sn99** [comment]
- [ ] Add more examples in `README`

@DeviousCilantro Can we redistribute `pledge` binary with this repo? Local availability would be better considering we might deploy it in a restricted environment. Some sort of `--local-pledge` arg or something. What are your thoughts?

**Comment by DeviousCilantro** [comment]
Yes, that is a good idea. I will make the binary locally available with the repo but also preserve the option of using `wget` to fetch from upstream for those who might want to do so. As usual, the argument provided will determine whether the local or remote version is used during execution.

**Comment by DeviousCilantro** [comment]
@sn99 Hi, can this issue be closed if the PR I submitted for review and merge resolves it? The tasks listed have all been completed. Feel free to have a look.
